### ISSUE TITLE
Firebase key setup

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/support#24]
**Description**

I'm having trouble configuring eddiebot for testing. Not sure if I'm using the wrong key / or incorrect config file. 
I've tried service key, server key, API key. 

Tried:
```
export DISCORD_TOKEN=myDiscordKey
export COMMAND_PREFIX='^'
export DISCORD_SERVER_ID=myServerKey
export DISCORD_BOT_CHANNEL_ID=myChannelID
export FIREBASE_KEY='~/code/eddie/firebase-adminsdk.json'
```

Tried: 
```
export FIREBASE_KEY=myRawKey
```

**Stack**

Node.js Typescript Discord.js

**Working Environment**

OpenSuse Linux

Error:
```

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/ren/code/eddie/EddieBot/dist/firebase.js:5:47)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ren/code/eddie/EddieBot/dist/commandHandlers/bio.js:7:20)
```
Another Error
```
src/firebase.ts:6:9 - error TS2345: Argument of type '{ apiKey: string; authDomain: string; databaseURL: string; projectId: string; storageBucket: string; messagingSenderId: string; appId: string; }' is not assignable to parameter of type 'string | ServiceAccount'.
  Object literal may only specify known properties, and 'apiKey' does not exist in type 'ServiceAccount'.

6         apiKey: "myKey",
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by eddiejaoude** [comment]
@AllanRegush thank you for the questions, apologies if the documentation are missing some information, we will improve it together

I think your key is not value json, my environment variable for the firebase key looks like...

```
export FIREBASE_KEY='{"type": "service_account","project_id": ... }'
```

**Comment by AllanRegush** [comment]
Thanks @eddiejaoude. I was able to get the bot working with your example.
